USE [master]
GO

/****** Object:  Database [LSIWebPortalDB]    Script Date: 12-09-2017 10:32:08 ******/
CREATE DATABASE [LSIWebPortalDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LSIWebPortalDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\LSIWebPortalDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LSIWebPortalDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\LSIWebPortalDB_log.ldf' , SIZE = 3456KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LSIWebPortalDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LSIWebPortalDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LSIWebPortalDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LSIWebPortalDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LSIWebPortalDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LSIWebPortalDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LSIWebPortalDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [LSIWebPortalDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LSIWebPortalDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LSIWebPortalDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LSIWebPortalDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LSIWebPortalDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LSIWebPortalDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LSIWebPortalDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LSIWebPortalDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LSIWebPortalDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LSIWebPortalDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LSIWebPortalDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LSIWebPortalDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LSIWebPortalDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LSIWebPortalDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LSIWebPortalDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LSIWebPortalDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LSIWebPortalDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LSIWebPortalDB] SET RECOVERY FULL 
GO

ALTER DATABASE [LSIWebPortalDB] SET  MULTI_USER 
GO

ALTER DATABASE [LSIWebPortalDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LSIWebPortalDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LSIWebPortalDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LSIWebPortalDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LSIWebPortalDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LSIWebPortalDB] SET QUERY_STORE = OFF
GO

USE [LSIWebPortalDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [LSIWebPortalDB] SET  READ_WRITE 
GO

